kind: Service
apiVersion: v1
metadata:
  name: {{ template "node-chart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "node-chart.fullname" . }}-node
  ports:
    - port: 8080
      targetPort: 8080
