apiVersion: v2
name: node-chart
description: A Helm chart for sample node Js application
type: application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: mongodb
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 5.3.4
